---
dependencies:
  - role: sansible.users_and_groups
    sansible_users_and_groups_groups:
      - name: "{{ JAVAAPP_GROUP }}"
    sansible_users_and_groups_users:
      - name: "{{ JAVAAPP_USER }}"
        group: "{{ JAVAAPP_GROUP }}"
