---

galaxy_info:
  author: sansible
  description: "Installs Sonatype Nexus"
  license: MIT
  min_ansible_version: 2.5
  min_ansible_container_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - development
    - cd

dependencies:
  - role: sansible.users_and_groups
    sansible_users_and_groups_groups:
      - name: "{{ sansible_nexus_group }}"
    sansible_users_and_groups_users:
      - name: "{{ sansible_nexus_user }}"
        group: "{{ sansible_nexus_group }}"
