---
- name: download latest artifact from Nexus
  get_url:
    url: http://{{ nexus_server_ip }}:{{ nexus_server_port }}/service/rest/v1/search/assets/download?sort=version&repository={{ maven_repository }}&maven.groupId={{ maven_groupid }}&maven.artifactId={{ maven_artifactid }}&maven.extension={{ maven_extention }}
    dest: /home/{{ java_app_user }}/temp.jar
    force: yes
    # force_basic_auth: yes
    # username: ==I prefer not to provide credentials here and use anonymouse
    # password: ==Nexus access instead because this role should be on GitHub

- name: install latest artifact as systemd service
  template:
    src: javapp.service.j2
    dest: /etc/systemd/system/{{ systemd_service_name }}.service

- name: run {{ systemd_service_name }} service
  systemd:
    name: "{{ systemd_service_name }}"
    state: restarted
    daemon_reload: yes
