---
- name: download latest artifact from Nexus
  get_url:
    url: http://{{ NEXUS_SERVER_IP }}:{{ NEXUS_SERVER_PORT }}/service/rest/v1/search/assets/download?sort=version&repository={{ MAVEN_REPOSTITORY }}&maven.groupId={{ MAVEN_GROUPID }}&maven.artifactId={{ MAVEN_ARTIFACTID }}&maven.extension={{ MAVEN_EXTENTION }}
    dest: /home/{{ JAVAAPP_USER }}/temp.jar
    force: yes  # will download the file every time and replace the file if the contents change
    # force_basic_auth: yes
    # username: ==I prefer not to provide credentials here and use anonymouse
    # password: ==Nexus access instead because this role should be on GitHub

- name: install latest artifact as systemd service
  template:
    src: javapp.service.j2
    dest: /etc/systemd/system/{{ SYSTEMD_SERVICE_NAME }}.service

- name: run {{ SYSTEMD_SERVICE_NAME }} service
  systemd:
    name: "{{ SYSTEMD_SERVICE_NAME }}"
    state: restarted
    daemon_reload: yes
