---
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ centos_version }}.noarch.rpm"
epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ centos_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
