FROM openjdk:8-jre-alpine
LABEL maintainer="Pavlo F. pavel.lucik@gmail.com"
ADD http://{{ nexus_server_ip }}:{{ nexus_server_port }}/service/rest/v1/search/assets/download?sort=version&repository={{ maven_repository }}&maven.groupId={{ maven_groupid }}&maven.artifactId={{ maven_artifactid }}&maven.extension={{ maven_extention }} /javapp.jar
EXPOSE {{ javapp_service_port }}
ENTRYPOINT ["/usr/bin/java", "-jar", "/javapp.jar"]
