---
- name: check if Docker is installed
  package_facts:
    manager: "auto"

- name: disable Docker service autostart on CentOS
  service:
    name: docker
    enabled: no
  when: "'docker-ce' in ansible_facts.packages"

- name: disable Docker service autostart on Amazon Linux2
  service:
    name: docker
    enabled: no
  when: "'docker' in ansible_facts.packages"
