---
- name: Check if Docker is installed
  package_facts:
    manager: "auto"

- name: Enable Docker service autostart on CentOS
  service:
    name: docker
    enabled: yes
  when: "'docker-ce' in ansible_facts.packages"

- name: Enable Docker service autostart on Amazon Linux2
  service:
    name: docker
    enabled: yes
  when: "'docker' in ansible_facts.packages"
