---
- name: Check if Docker is installed
  package_facts:
    manager: "auto"

- name: Start Docker service on CentOS
  service:
    name: docker
    state: started
  when: "'docker-ce' in ansible_facts.packages"

- name: Start Docker service on Amazon Linux2
  service:
    name: docker
    state: started
  when: "'docker' in ansible_facts.packages"
