- name: uninstall older versions of Docker
  yum:
   name: "{{ item }}"
   state: absent
   update_cache: yes
  loop:
    "{{ uninstall_old_list }}"
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'
