FROM openjdk:8-jre-alpine
LABEL maintainer="Evgeniy Naryshkin evgeniy-naryshkin@gmail.com"
ADD http://{{ NEXUS_SERVER_IP }}:{{ NEXUS_SERVER_PORT }}/service/rest/v1/search/assets/download?sort=version&repository={{ MAVEN_REPOSITORY }}&maven.groupId={{ MAVEN_GROUPID }}&maven.artifactId={{ MAVEN_ARTIFACTID }}&maven.extension={{ MAVEN_EXTENTION }} /javapp.jar
EXPOSE {{ JAVAAPP_SERVICE_PORT }}
ENTRYPOINT ["/usr/bin/java", "-jar", "/javapp.jar"]
