---
- name: copy Dockerfile
  template:
    src: Dockerfile.j2
    dest: /home/{{ docker_user }}/Dockerfile

- name: build docker image
  become_user: docker
  become: true
  command: "docker build -f /home/{{ docker_user }}/Dockerfile ."
